/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as PrayRouteImport } from './routes/pray'
import { Route as PhasesRouteImport } from './routes/phases'
import { Route as MissionariesRouteImport } from './routes/missionaries'
import { Route as MapRouteImport } from './routes/map'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionariesIndexRouteImport } from './routes/missionaries.index'
import { Route as MissionariesIdRouteImport } from './routes/missionaries.$id'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayRoute = PrayRouteImport.update({
  id: '/pray',
  path: '/pray',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasesRoute = PhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionariesRoute = MissionariesRouteImport.update({
  id: '/missionaries',
  path: '/missionaries',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionariesIndexRoute = MissionariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MissionariesRoute,
} as any)
const MissionariesIdRoute = MissionariesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MissionariesRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import': typeof ImportRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/missionaries': typeof MissionariesRouteWithChildren
  '/phases': typeof PhasesRoute
  '/pray': typeof PrayRoute
  '/prayer': typeof PrayerRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summaries': typeof SummariesRoute
  '/support': typeof SupportRoute
  '/admin/roles': typeof AdminRolesRoute
  '/missionaries/$id': typeof MissionariesIdRoute
  '/missionaries/': typeof MissionariesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import': typeof ImportRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/phases': typeof PhasesRoute
  '/pray': typeof PrayRoute
  '/prayer': typeof PrayerRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summaries': typeof SummariesRoute
  '/support': typeof SupportRoute
  '/admin/roles': typeof AdminRolesRoute
  '/missionaries/$id': typeof MissionariesIdRoute
  '/missionaries': typeof MissionariesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/documents': typeof DocumentsRoute
  '/import': typeof ImportRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/missionaries': typeof MissionariesRouteWithChildren
  '/phases': typeof PhasesRoute
  '/pray': typeof PrayRoute
  '/prayer': typeof PrayerRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summaries': typeof SummariesRoute
  '/support': typeof SupportRoute
  '/admin/roles': typeof AdminRolesRoute
  '/missionaries/$id': typeof MissionariesIdRoute
  '/missionaries/': typeof MissionariesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/documents'
    | '/import'
    | '/manage'
    | '/map'
    | '/missionaries'
    | '/phases'
    | '/pray'
    | '/prayer'
    | '/reports'
    | '/sitemap.xml'
    | '/summaries'
    | '/support'
    | '/admin/roles'
    | '/missionaries/$id'
    | '/missionaries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/documents'
    | '/import'
    | '/manage'
    | '/map'
    | '/phases'
    | '/pray'
    | '/prayer'
    | '/reports'
    | '/sitemap.xml'
    | '/summaries'
    | '/support'
    | '/admin/roles'
    | '/missionaries/$id'
    | '/missionaries'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/documents'
    | '/import'
    | '/manage'
    | '/map'
    | '/missionaries'
    | '/phases'
    | '/pray'
    | '/prayer'
    | '/reports'
    | '/sitemap.xml'
    | '/summaries'
    | '/support'
    | '/admin/roles'
    | '/missionaries/$id'
    | '/missionaries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DocumentsRoute: typeof DocumentsRoute
  ImportRoute: typeof ImportRoute
  ManageRoute: typeof ManageRoute
  MapRoute: typeof MapRoute
  MissionariesRoute: typeof MissionariesRouteWithChildren
  PhasesRoute: typeof PhasesRoute
  PrayRoute: typeof PrayRoute
  PrayerRoute: typeof PrayerRoute
  ReportsRoute: typeof ReportsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SummariesRoute: typeof SummariesRoute
  SupportRoute: typeof SupportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pray': {
      id: '/pray'
      path: '/pray'
      fullPath: '/pray'
      preLoaderRoute: typeof PrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phases': {
      id: '/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof PhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missionaries': {
      id: '/missionaries'
      path: '/missionaries'
      fullPath: '/missionaries'
      preLoaderRoute: typeof MissionariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missionaries/': {
      id: '/missionaries/'
      path: '/'
      fullPath: '/missionaries/'
      preLoaderRoute: typeof MissionariesIndexRouteImport
      parentRoute: typeof MissionariesRoute
    }
    '/missionaries/$id': {
      id: '/missionaries/$id'
      path: '/$id'
      fullPath: '/missionaries/$id'
      preLoaderRoute: typeof MissionariesIdRouteImport
      parentRoute: typeof MissionariesRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRolesRoute: typeof AdminRolesRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRolesRoute: AdminRolesRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MissionariesRouteChildren {
  MissionariesIdRoute: typeof MissionariesIdRoute
  MissionariesIndexRoute: typeof MissionariesIndexRoute
}

const MissionariesRouteChildren: MissionariesRouteChildren = {
  MissionariesIdRoute: MissionariesIdRoute,
  MissionariesIndexRoute: MissionariesIndexRoute,
}

const MissionariesRouteWithChildren = MissionariesRoute._addFileChildren(
  MissionariesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DocumentsRoute: DocumentsRoute,
  ImportRoute: ImportRoute,
  ManageRoute: ManageRoute,
  MapRoute: MapRoute,
  MissionariesRoute: MissionariesRouteWithChildren,
  PhasesRoute: PhasesRoute,
  PrayRoute: PrayRoute,
  PrayerRoute: PrayerRoute,
  ReportsRoute: ReportsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SummariesRoute: SummariesRoute,
  SupportRoute: SupportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
