/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as PrayRouteImport } from './routes/pray'
import { Route as PhasesRouteImport } from './routes/phases'
import { Route as MissionariesRouteImport } from './routes/missionaries'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MapRouteImport } from './routes/map'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as BrilliantRouteImport } from './routes/brilliant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MissionariesIndexRouteImport } from './routes/missionaries.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MissionariesIdRouteImport } from './routes/missionaries.$id'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminMonthlyRouteImport } from './routes/admin.monthly'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice.transcribe'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice.speak'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayRoute = PrayRouteImport.update({
  id: '/pray',
  path: '/pray',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasesRoute = PhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionariesRoute = MissionariesRouteImport.update({
  id: '/missionaries',
  path: '/missionaries',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const BrilliantRoute = BrilliantRouteImport.update({
  id: '/brilliant',
  path: '/brilliant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionariesIndexRoute = MissionariesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MissionariesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MissionariesIdRoute = MissionariesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MissionariesRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonthlyRoute = AdminMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/brilliant': typeof BrilliantRoute
  '/documents': typeof DocumentsRoute
  '/import': typeof ImportRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/missionaries': typeof MissionariesRouteWithChildren
  '/phases': typeof PhasesRoute
  '/pray': typeof PrayRoute
  '/prayer': typeof PrayerRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summaries': typeof SummariesRoute
  '/support': typeof SupportRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/monthly': typeof AdminMonthlyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/missionaries/$id': typeof MissionariesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/missionaries/': typeof MissionariesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/brilliant': typeof BrilliantRoute
  '/documents': typeof DocumentsRoute
  '/import': typeof ImportRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/phases': typeof PhasesRoute
  '/pray': typeof PrayRoute
  '/prayer': typeof PrayerRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summaries': typeof SummariesRoute
  '/support': typeof SupportRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/monthly': typeof AdminMonthlyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/missionaries/$id': typeof MissionariesIdRoute
  '/admin': typeof AdminIndexRoute
  '/missionaries': typeof MissionariesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/brilliant': typeof BrilliantRoute
  '/documents': typeof DocumentsRoute
  '/import': typeof ImportRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/mcp': typeof McpRoute
  '/missionaries': typeof MissionariesRouteWithChildren
  '/phases': typeof PhasesRoute
  '/pray': typeof PrayRoute
  '/prayer': typeof PrayerRoute
  '/records': typeof RecordsRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/summaries': typeof SummariesRoute
  '/support': typeof SupportRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/monthly': typeof AdminMonthlyRoute
  '/admin/roles': typeof AdminRolesRoute
  '/missionaries/$id': typeof MissionariesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/missionaries/': typeof MissionariesIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/brilliant'
    | '/documents'
    | '/import'
    | '/manage'
    | '/map'
    | '/mcp'
    | '/missionaries'
    | '/phases'
    | '/pray'
    | '/prayer'
    | '/records'
    | '/reports'
    | '/sitemap.xml'
    | '/summaries'
    | '/support'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/activity'
    | '/admin/monthly'
    | '/admin/roles'
    | '/missionaries/$id'
    | '/admin/'
    | '/missionaries/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/brilliant'
    | '/documents'
    | '/import'
    | '/manage'
    | '/map'
    | '/mcp'
    | '/phases'
    | '/pray'
    | '/prayer'
    | '/records'
    | '/reports'
    | '/sitemap.xml'
    | '/summaries'
    | '/support'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/activity'
    | '/admin/monthly'
    | '/admin/roles'
    | '/missionaries/$id'
    | '/admin'
    | '/missionaries'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/auth'
    | '/brilliant'
    | '/documents'
    | '/import'
    | '/manage'
    | '/map'
    | '/mcp'
    | '/missionaries'
    | '/phases'
    | '/pray'
    | '/prayer'
    | '/records'
    | '/reports'
    | '/sitemap.xml'
    | '/summaries'
    | '/support'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/activity'
    | '/admin/monthly'
    | '/admin/roles'
    | '/missionaries/$id'
    | '/admin/'
    | '/missionaries/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  BrilliantRoute: typeof BrilliantRoute
  DocumentsRoute: typeof DocumentsRoute
  ImportRoute: typeof ImportRoute
  ManageRoute: typeof ManageRoute
  MapRoute: typeof MapRoute
  McpRoute: typeof McpRoute
  MissionariesRoute: typeof MissionariesRouteWithChildren
  PhasesRoute: typeof PhasesRoute
  PrayRoute: typeof PrayRoute
  PrayerRoute: typeof PrayerRoute
  RecordsRoute: typeof RecordsRoute
  ReportsRoute: typeof ReportsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SummariesRoute: typeof SummariesRoute
  SupportRoute: typeof SupportRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pray': {
      id: '/pray'
      path: '/pray'
      fullPath: '/pray'
      preLoaderRoute: typeof PrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phases': {
      id: '/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof PhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missionaries': {
      id: '/missionaries'
      path: '/missionaries'
      fullPath: '/missionaries'
      preLoaderRoute: typeof MissionariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brilliant': {
      id: '/brilliant'
      path: '/brilliant'
      fullPath: '/brilliant'
      preLoaderRoute: typeof BrilliantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missionaries/': {
      id: '/missionaries/'
      path: '/'
      fullPath: '/missionaries/'
      preLoaderRoute: typeof MissionariesIndexRouteImport
      parentRoute: typeof MissionariesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/missionaries/$id': {
      id: '/missionaries/$id'
      path: '/$id'
      fullPath: '/missionaries/$id'
      preLoaderRoute: typeof MissionariesIdRouteImport
      parentRoute: typeof MissionariesRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monthly': {
      id: '/admin/monthly'
      path: '/monthly'
      fullPath: '/admin/monthly'
      preLoaderRoute: typeof AdminMonthlyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminMonthlyRoute: typeof AdminMonthlyRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminMonthlyRoute: AdminMonthlyRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MissionariesRouteChildren {
  MissionariesIdRoute: typeof MissionariesIdRoute
  MissionariesIndexRoute: typeof MissionariesIndexRoute
}

const MissionariesRouteChildren: MissionariesRouteChildren = {
  MissionariesIdRoute: MissionariesIdRoute,
  MissionariesIndexRoute: MissionariesIndexRoute,
}

const MissionariesRouteWithChildren = MissionariesRoute._addFileChildren(
  MissionariesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  BrilliantRoute: BrilliantRoute,
  DocumentsRoute: DocumentsRoute,
  ImportRoute: ImportRoute,
  ManageRoute: ManageRoute,
  MapRoute: MapRoute,
  McpRoute: McpRoute,
  MissionariesRoute: MissionariesRouteWithChildren,
  PhasesRoute: PhasesRoute,
  PrayRoute: PrayRoute,
  PrayerRoute: PrayerRoute,
  RecordsRoute: RecordsRoute,
  ReportsRoute: ReportsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SummariesRoute: SummariesRoute,
  SupportRoute: SupportRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
